# Generated by Django 2.1.1 on 2018-09-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('estilo', models.CharField(max_length=50)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('nota', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
