# Generated by Django 2.1.1 on 2018-09-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20180922_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='nota',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
